import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { aboutComparisonEn } from '../i18n/aboutComparison.en';
import { aboutComparisonEs } from '../i18n/aboutComparison.es';
import { aboutComparisonPt } from '../i18n/aboutComparison.pt';
import { aboutComparisonFr } from '../i18n/aboutComparison.fr';
import { aboutComparisonDe } from '../i18n/aboutComparison.de';
import { aboutComparisonJa } from '../i18n/aboutComparison.ja';
import { aboutComparisonZh } from '../i18n/aboutComparison.zh';

export type Language = 'en' | 'es' | 'pt' | 'fr' | 'de' | 'ja' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const VALID_LANGUAGES: Language[] = ['en', 'es', 'pt', 'fr', 'de', 'ja', 'zh'];

function isValidLanguage(lang: string): lang is Language {
  return VALID_LANGUAGES.includes(lang as Language);
}

function resolveInitialLanguage(): Language {
  const urlLang = new URLSearchParams(window.location.search).get('lang');
  if (urlLang && isValidLanguage(urlLang)) return urlLang;

  const saved = localStorage.getItem('katoa-language') || localStorage.getItem('bitwish-language');
  if (saved && isValidLanguage(saved)) return saved;

  const navLang = navigator.language?.split('-')[0]?.toLowerCase();
  if (navLang && isValidLanguage(navLang)) return navLang;

  return 'en';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const homeStrings = {
  en: {
    'home.badge': 'Bitcoin-native • Non-custodial • Open Source',
    'home.keep': 'Keep',
    'home.percent': '100%',
    'home.earnings': 'of Your Earnings',
    'home.subtitle': 'Zero-fee, privacy-first Bitcoin commerce.',
    'home.subtitle2': 'Protocol-level upgrade to creator monetization.',
    'home.cta.start': 'Start Earning 100%',
    'home.cta.compare': 'See How We Compare',
    'home.stats.processed': 'processed',
    'home.stats.countries': 'countries',
    'home.stats.fees': 'fees forever',
    'home.protocol': 'Protocol',
    'home.builtDifferent': 'Built Different',
    'home.fees.title': 'Stop Losing Thousands to Fees',
    'home.fees.subtitle': 'See how much you keep with KATOA vs traditional platforms.',
    'home.howItWorks.title': 'How It Works',
    'home.howItWorks.subtitle': 'From sign-up to your first sat in four steps',
    'home.step1.title': 'Create Account',
    'home.step1.desc': 'Sign up with email, Google, or Nostr — no bank account required.',
    'home.step2.title': 'Build Wishlist',
    'home.step2.desc': 'Add goals, media, and your story. Set sat prices for each item.',
    'home.step3.title': 'Share Your Link',
    'home.step3.desc': 'Post your page anywhere. QR codes make it easy for supporters.',
    'home.step4.title': 'Receive Bitcoin',
    'home.step4.desc': 'Donations land instantly in your wallet. Zero platform cut.',
    'home.join.title': 'Join the Bitcoin Creator Economy',
    'home.join.subtitle': 'Creators worldwide are stopping platform fees and building true financial freedom.',
    'home.join.cta': 'Get Started Free',
    'home.join.browse': 'Browse Campaigns',
    'home.howItWorks.eyebrow': 'How it works',
    'home.pillar1.title': 'Instant settlement',
    'home.pillar1.desc': 'Funds arrive over Bitcoin Lightning in seconds. No payment processor holding your money for weeks.',
    'home.pillar1.old': '7–14 days',
    'home.pillar1.next': 'Instant',
    'home.pillar2.title': 'Truly global',
    'home.pillar2.desc': 'Creators in 195+ countries. No bank account, no geographic gatekeeping, no Stripe exclusions.',
    'home.pillar2.old': '~10 countries',
    'home.pillar2.next': '195+ countries',
    'home.pillar3.title': 'Privacy by design',
    'home.pillar3.desc': 'Nostr-native identity, minimal data collection, and a roadmap toward stronger payment privacy.',
    'home.pillar3.old': 'Platform-owned',
    'home.pillar3.next': 'You own your keys',
    'home.bento.traditional': 'Traditional',
    'home.bento.katoa': 'KATOA',
    'home.cta.note': '0% platform fees. Lightning costs are minimal and usually paid by supporters. KATOA never custodies your balance.',
    'home.cta.launch': 'Launch',
    'home.cta.processed': 'Processed',
    'home.cta.fees': 'Fees',
  },
  es: {
    'home.badge': 'Nativo Bitcoin • No custodial • Código abierto',
    'home.keep': 'Conserva',
    'home.percent': '100%',
    'home.earnings': 'de tus ganancias',
    'home.subtitle': 'Comercio Bitcoin sin comisiones y con privacidad.',
    'home.subtitle2': 'Actualización a nivel de protocolo para monetización de creadores.',
    'home.cta.start': 'Empieza a ganar 100%',
    'home.cta.compare': 'Compara plataformas',
    'home.stats.processed': 'procesado',
    'home.stats.countries': 'países',
    'home.stats.fees': 'comisiones para siempre',
    'home.protocol': 'Protocolo',
    'home.builtDifferent': 'Construido diferente',
    'home.fees.title': 'Deja de perder miles en comisiones',
    'home.fees.subtitle': 'Mira cuánto conservas con KATOA vs plataformas tradicionales.',
    'home.howItWorks.title': 'Cómo funciona',
    'home.howItWorks.subtitle': 'Del registro a tu primer sat en cuatro pasos',
    'home.step1.title': 'Crear cuenta',
    'home.step1.desc': 'Regístrate con email, Google o Nostr — sin cuenta bancaria.',
    'home.step2.title': 'Crear lista',
    'home.step2.desc': 'Añade metas, medios y tu historia. Pon precios en sats.',
    'home.step3.title': 'Comparte tu enlace',
    'home.step3.desc': 'Publica tu página en cualquier lugar. Códigos QR facilitan el apoyo.',
    'home.step4.title': 'Recibe Bitcoin',
    'home.step4.desc': 'Las donaciones llegan al instante. Cero comisión de plataforma.',
    'home.join.title': 'Únete a la economía creadora Bitcoin',
    'home.join.subtitle': 'Creadores en todo el mundo dejan de pagar comisiones y ganan libertad financiera.',
    'home.join.cta': 'Empezar gratis',
    'home.join.browse': 'Explorar campañas',
  },
  pt: {
    'home.badge': 'Nativo Bitcoin • Não custodial • Código aberto',
    'home.keep': 'Fique com',
    'home.percent': '100%',
    'home.earnings': 'dos seus ganhos',
    'home.subtitle': 'Comércio Bitcoin sem taxas e com privacidade.',
    'home.subtitle2': 'Atualização em nível de protocolo para monetização de criadores.',
    'home.cta.start': 'Comece a ganhar 100%',
    'home.cta.compare': 'Compare plataformas',
    'home.stats.processed': 'processado',
    'home.stats.countries': 'países',
    'home.stats.fees': 'taxas para sempre',
    'home.protocol': 'Protocolo',
    'home.builtDifferent': 'Construído diferente',
    'home.fees.title': 'Pare de perder milhares em taxas',
    'home.fees.subtitle': 'Veja quanto você fica com KATOA vs plataformas tradicionais.',
    'home.howItWorks.title': 'Como funciona',
    'home.howItWorks.subtitle': 'Do cadastro ao seu primeiro sat em quatro passos',
    'home.step1.title': 'Criar conta',
    'home.step1.desc': 'Cadastre-se com email, Google ou Nostr — sem conta bancária.',
    'home.step2.title': 'Montar lista',
    'home.step2.desc': 'Adicione metas, mídia e sua história. Defina preços em sats.',
    'home.step3.title': 'Compartilhe o link',
    'home.step3.desc': 'Publique sua página em qualquer lugar. QR codes facilitam o apoio.',
    'home.step4.title': 'Receba Bitcoin',
    'home.step4.desc': 'Doações chegam na hora. Zero taxa de plataforma.',
    'home.join.title': 'Junte-se à economia criativa Bitcoin',
    'home.join.subtitle': 'Criadores no mundo todo param de pagar taxas e ganham liberdade financeira.',
    'home.join.cta': 'Começar grátis',
    'home.join.browse': 'Ver campanhas',
  },
  fr: {
    'home.badge': 'Bitcoin natif • Non custodial • Open source',
    'home.keep': 'Gardez',
    'home.percent': '100%',
    'home.earnings': 'de vos revenus',
    'home.subtitle': 'Commerce Bitcoin sans frais et axé sur la confidentialité.',
    'home.subtitle2': 'Mise à niveau au niveau protocole pour la monétisation des créateurs.',
    'home.cta.start': 'Gagnez 100%',
    'home.cta.compare': 'Comparer les plateformes',
    'home.stats.processed': 'traité',
    'home.stats.countries': 'pays',
    'home.stats.fees': 'frais pour toujours',
    'home.protocol': 'Protocole',
    'home.builtDifferent': 'Conçu différemment',
    'home.fees.title': 'Arrêtez de perdre des milliers en frais',
    'home.fees.subtitle': 'Voyez combien vous gardez avec KATOA vs les plateformes traditionnelles.',
    'home.howItWorks.title': 'Comment ça marche',
    'home.howItWorks.subtitle': 'De l\'inscription à votre premier sat en quatre étapes',
    'home.step1.title': 'Créer un compte',
    'home.step1.desc': 'Inscrivez-vous par email, Google ou Nostr — sans compte bancaire.',
    'home.step2.title': 'Créer une liste',
    'home.step2.desc': 'Ajoutez objectifs, médias et votre histoire. Fixez des prix en sats.',
    'home.step3.title': 'Partagez votre lien',
    'home.step3.desc': 'Publiez votre page partout. Les QR codes facilitent le soutien.',
    'home.step4.title': 'Recevez du Bitcoin',
    'home.step4.desc': 'Les dons arrivent instantanément. Zéro commission plateforme.',
    'home.join.title': 'Rejoignez l\'économie créative Bitcoin',
    'home.join.subtitle': 'Les créateurs du monde entier arrêtent les frais et gagnent en liberté financière.',
    'home.join.cta': 'Commencer gratuitement',
    'home.join.browse': 'Parcourir les campagnes',
  },
  de: {
    'home.badge': 'Bitcoin-nativ • Nicht-verwahrend • Open Source',
    'home.keep': 'Behalte',
    'home.percent': '100%',
    'home.earnings': 'deiner Einnahmen',
    'home.subtitle': 'Gebührenfreier, datenschutzorientierter Bitcoin-Handel.',
    'home.subtitle2': 'Protokoll-Level-Upgrade für Creator-Monetarisierung.',
    'home.cta.start': 'Verdiene 100%',
    'home.cta.compare': 'Plattformen vergleichen',
    'home.stats.processed': 'verarbeitet',
    'home.stats.countries': 'Länder',
    'home.stats.fees': 'Gebühren für immer',
    'home.protocol': 'Protokoll',
    'home.builtDifferent': 'Anders gebaut',
    'home.fees.title': 'Hör auf, Tausende an Gebühren zu verlieren',
    'home.fees.subtitle': 'Sieh, wie viel du mit KATOA vs. traditionellen Plattformen behältst.',
    'home.howItWorks.title': 'So funktioniert\'s',
    'home.howItWorks.subtitle': 'Von der Anmeldung bis zu deinem ersten Sat in vier Schritten',
    'home.step1.title': 'Konto erstellen',
    'home.step1.desc': 'Registriere dich per E-Mail, Google oder Nostr — ohne Bankkonto.',
    'home.step2.title': 'Wunschliste erstellen',
    'home.step2.desc': 'Füge Ziele, Medien und deine Geschichte hinzu. Setze Sat-Preise.',
    'home.step3.title': 'Link teilen',
    'home.step3.desc': 'Poste deine Seite überall. QR-Codes erleichtern die Unterstützung.',
    'home.step4.title': 'Bitcoin empfangen',
    'home.step4.desc': 'Spenden landen sofort in deiner Wallet. Null Plattformgebühr.',
    'home.join.title': 'Tritt der Bitcoin-Creator-Ökonomie bei',
    'home.join.subtitle': 'Creator weltweit stoppen Plattformgebühren und gewinnen finanzielle Freiheit.',
    'home.join.cta': 'Kostenlos starten',
    'home.join.browse': 'Kampagnen durchsuchen',
  },
  ja: {
    'home.badge': 'Bitcoinネイティブ • 非カストディアル • オープンソース',
    'home.keep': '手取り',
    'home.percent': '100%',
    'home.earnings': 'をキープ',
    'home.subtitle': '手数料ゼロ、プライバシー重視のBitcoinコマース。',
    'home.subtitle2': 'クリエイター収益化のプロトコルレベルアップグレード。',
    'home.cta.start': '100%を稼ぎ始める',
    'home.cta.compare': '他社と比較',
    'home.stats.processed': '処理済み',
    'home.stats.countries': 'カ国',
    'home.stats.fees': '手数料永久ゼロ',
    'home.protocol': 'プロトコル',
    'home.builtDifferent': '違う設計',
    'home.fees.title': '手数料で数千ドル失うのをやめよう',
    'home.fees.subtitle': 'KATOAと従来のプラットフォームで手取りを比較。',
    'home.howItWorks.title': '使い方',
    'home.howItWorks.subtitle': '登録から最初のsatまで4ステップ',
    'home.step1.title': 'アカウント作成',
    'home.step1.desc': 'メール、Google、Nostrで登録 — 銀行口座不要。',
    'home.step2.title': 'ウィッシュリスト作成',
    'home.step2.desc': '目標、メディア、ストーリーを追加。sats価格を設定。',
    'home.step3.title': 'リンクを共有',
    'home.step3.desc': 'どこでもページを投稿。QRコードで支援しやすく。',
    'home.step4.title': 'Bitcoinを受け取る',
    'home.step4.desc': '寄付は即座にウォレットへ。プラットフォーム手数料ゼロ。',
    'home.join.title': 'Bitcoinクリエイター経済に参加',
    'home.join.subtitle': '世界中のクリエイターが手数料をやめ、経済的自由を手に入れています。',
    'home.join.cta': '無料で始める',
    'home.join.browse': 'キャンペーンを見る',
  },
  zh: {
    'home.badge': '比特币原生 • 非托管 • 开源',
    'home.keep': '保留',
    'home.percent': '100%',
    'home.earnings': '的收入',
    'home.subtitle': '零费用、隐私优先的比特币商务。',
    'home.subtitle2': '创作者变现的协议级升级。',
    'home.cta.start': '开始赚取100%',
    'home.cta.compare': '查看平台对比',
    'home.stats.processed': '已处理',
    'home.stats.countries': '个国家',
    'home.stats.fees': '永久零费用',
    'home.protocol': '协议',
    'home.builtDifferent': '与众不同',
    'home.fees.title': '别再因手续费损失数千美元',
    'home.fees.subtitle': '看看KATOA与传统平台相比你能保留多少。',
    'home.howItWorks.title': '如何运作',
    'home.howItWorks.subtitle': '从注册到收到第一个聪，只需四步',
    'home.step1.title': '创建账户',
    'home.step1.desc': '用邮箱、Google或Nostr注册 — 无需银行账户。',
    'home.step2.title': '建立心愿单',
    'home.step2.desc': '添加目标、媒体和故事。为每项设置聪价格。',
    'home.step3.title': '分享链接',
    'home.step3.desc': '在任何地方发布页面。二维码让支持者更容易找到你。',
    'home.step4.title': '接收比特币',
    'home.step4.desc': '捐款即时到账。零平台抽成。',
    'home.join.title': '加入比特币创作者经济',
    'home.join.subtitle': '全球创作者正在停止支付平台费用，获得真正的财务自由。',
    'home.join.cta': '免费开始',
    'home.join.browse': '浏览活动',
  },
};

const navUiStrings = {
  en: {
    'nav.comparison': 'Why KATOA?',
    'nav.home': 'Home',
    'nav.more': 'More',
    'nav.signOut': 'Sign Out',
    'nav.faq': 'FAQ',
    'nav.menu': 'KATOA Menu',
    'nav.getStarted': 'Get Started Free',
    'nav.changeLanguage': 'Change language',
    'nav.chooseLanguage': 'Choose Language',
    'nav.currency': 'Currency',
    'nav.btcPrice': 'BTC Price',
    'nav.tapProfile': 'Tap to view profile',
    'nav.closeMenu': 'Close menu',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'Demo mode — explore with sample data. No account required.',
    'demo.tryWishlist': 'Try demo wishlist →',
    'pwa.installTitle': 'Add KATOA to Home Screen',
    'pwa.installSubtitle': 'Quick access, app-like experience.',
    'pwa.install': 'Install',
    'pwa.dismiss': 'Dismiss',
    'changelog.gotIt': 'Got it',
    'changelog.whatsNew': "What's new in",
    'common.backHome': 'Back to Home',
    'wishlist.title': 'Wishlist',
    'auth.passwordWeak': 'Weak password',
    'auth.passwordMedium': 'Medium strength',
    'auth.passwordStrong': 'Strong password',
  },
  es: {
    'nav.comparison': '¿Por qué KATOA?',
    'nav.home': 'Inicio',
    'nav.more': 'Más',
    'nav.signOut': 'Cerrar sesión',
    'nav.faq': 'FAQ',
    'nav.menu': 'Menú KATOA',
    'nav.getStarted': 'Empezar gratis',
    'nav.changeLanguage': 'Cambiar idioma',
    'nav.chooseLanguage': 'Elegir idioma',
    'nav.currency': 'Moneda',
    'nav.btcPrice': 'Precio BTC',
    'nav.tapProfile': 'Toca para ver perfil',
    'nav.closeMenu': 'Cerrar menú',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'Modo demo — explora con datos de ejemplo. Sin cuenta.',
    'demo.tryWishlist': 'Probar wishlist demo →',
    'pwa.installTitle': 'Añadir KATOA a inicio',
    'pwa.installSubtitle': 'Acceso rápido, experiencia tipo app.',
    'pwa.install': 'Instalar',
    'pwa.dismiss': 'Descartar',
    'changelog.gotIt': 'Entendido',
    'changelog.whatsNew': 'Novedades en',
    'common.backHome': 'Volver al inicio',
    'wishlist.title': 'Wishlist',
    'auth.passwordWeak': 'Contraseña débil',
    'auth.passwordMedium': 'Contraseña media',
    'auth.passwordStrong': 'Contraseña fuerte',
  },
  pt: {
    'nav.comparison': 'Por que KATOA?',
    'nav.home': 'Início',
    'nav.more': 'Mais',
    'nav.signOut': 'Sair',
    'nav.faq': 'FAQ',
    'nav.menu': 'Menu KATOA',
    'nav.getStarted': 'Começar grátis',
    'nav.changeLanguage': 'Mudar idioma',
    'nav.chooseLanguage': 'Escolher idioma',
    'nav.currency': 'Moeda',
    'nav.btcPrice': 'Preço BTC',
    'nav.tapProfile': 'Toque para ver perfil',
    'nav.closeMenu': 'Fechar menu',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'Modo demo — explore com dados de exemplo. Sem conta.',
    'demo.tryWishlist': 'Testar wishlist demo →',
    'pwa.installTitle': 'Adicionar KATOA à tela inicial',
    'pwa.installSubtitle': 'Acesso rápido, experiência de app.',
    'pwa.install': 'Instalar',
    'pwa.dismiss': 'Dispensar',
    'changelog.gotIt': 'Entendi',
    'changelog.whatsNew': 'Novidades em',
    'common.backHome': 'Voltar ao início',
    'wishlist.title': 'Wishlist',
    'auth.passwordWeak': 'Senha fraca',
    'auth.passwordMedium': 'Senha média',
    'auth.passwordStrong': 'Senha forte',
  },
  fr: {
    'nav.comparison': 'Pourquoi KATOA ?',
    'nav.home': 'Accueil',
    'nav.more': 'Plus',
    'nav.signOut': 'Déconnexion',
    'nav.faq': 'FAQ',
    'nav.menu': 'Menu KATOA',
    'nav.getStarted': 'Commencer gratuitement',
    'nav.changeLanguage': 'Changer de langue',
    'nav.chooseLanguage': 'Choisir la langue',
    'nav.currency': 'Devise',
    'nav.btcPrice': 'Prix BTC',
    'nav.tapProfile': 'Appuyer pour voir le profil',
    'nav.closeMenu': 'Fermer le menu',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'Mode démo — explorez avec des données exemple. Sans compte.',
    'demo.tryWishlist': 'Essayer la wishlist démo →',
    'pwa.installTitle': 'Ajouter KATOA à l\'écran d\'accueil',
    'pwa.installSubtitle': 'Accès rapide, expérience type app.',
    'pwa.install': 'Installer',
    'pwa.dismiss': 'Ignorer',
    'changelog.gotIt': 'Compris',
    'changelog.whatsNew': 'Nouveautés dans',
    'common.backHome': 'Retour à l\'accueil',
    'wishlist.title': 'Wishlist',
    'auth.passwordWeak': 'Mot de passe faible',
    'auth.passwordMedium': 'Mot de passe moyen',
    'auth.passwordStrong': 'Mot de passe fort',
  },
  de: {
    'nav.comparison': 'Warum KATOA?',
    'nav.home': 'Start',
    'nav.more': 'Mehr',
    'nav.signOut': 'Abmelden',
    'nav.faq': 'FAQ',
    'nav.menu': 'KATOA Menü',
    'nav.getStarted': 'Kostenlos starten',
    'nav.changeLanguage': 'Sprache ändern',
    'nav.chooseLanguage': 'Sprache wählen',
    'nav.currency': 'Währung',
    'nav.btcPrice': 'BTC-Preis',
    'nav.tapProfile': 'Tippen für Profil',
    'nav.closeMenu': 'Menü schließen',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'Demo-Modus — mit Beispieldaten erkunden. Kein Konto nötig.',
    'demo.tryWishlist': 'Demo-Wishlist testen →',
    'pwa.installTitle': 'KATOA zum Startbildschirm hinzufügen',
    'pwa.installSubtitle': 'Schneller Zugriff, App-Erlebnis.',
    'pwa.install': 'Installieren',
    'pwa.dismiss': 'Schließen',
    'changelog.gotIt': 'Verstanden',
    'changelog.whatsNew': 'Neu in',
    'common.backHome': 'Zurück zur Startseite',
    'wishlist.title': 'Wishlist',
    'auth.passwordWeak': 'Schwaches Passwort',
    'auth.passwordMedium': 'Mittlere Stärke',
    'auth.passwordStrong': 'Starkes Passwort',
  },
  ja: {
    'nav.comparison': 'なぜKATOA？',
    'nav.home': 'ホーム',
    'nav.more': 'その他',
    'nav.signOut': 'ログアウト',
    'nav.faq': 'FAQ',
    'nav.menu': 'KATOAメニュー',
    'nav.getStarted': '無料で始める',
    'nav.changeLanguage': '言語を変更',
    'nav.chooseLanguage': '言語を選択',
    'nav.currency': '通貨',
    'nav.btcPrice': 'BTC価格',
    'nav.tapProfile': 'タップしてプロフィールを表示',
    'nav.closeMenu': 'メニューを閉じる',
    'nav.faqLink': 'FAQ',
    'demo.banner': 'デモモード — サンプルデータで探索。アカウント不要。',
    'demo.tryWishlist': 'デモウィッシュリストを試す →',
    'pwa.installTitle': 'KATOAをホーム画面に追加',
    'pwa.installSubtitle': 'クイックアクセス、アプリのような体験。',
    'pwa.install': 'インストール',
    'pwa.dismiss': '閉じる',
    'changelog.gotIt': '了解',
    'changelog.whatsNew': '新機能',
    'common.backHome': 'ホームに戻る',
    'wishlist.title': 'ウィッシュリスト',
    'auth.passwordWeak': '弱いパスワード',
    'auth.passwordMedium': '中程度の強度',
    'auth.passwordStrong': '強いパスワード',
  },
  zh: {
    'nav.comparison': '为什么选择KATOA？',
    'nav.home': '首页',
    'nav.more': '更多',
    'nav.signOut': '退出登录',
    'nav.faq': '常见问题',
    'nav.menu': 'KATOA菜单',
    'nav.getStarted': '免费开始',
    'nav.changeLanguage': '更改语言',
    'nav.chooseLanguage': '选择语言',
    'nav.currency': '货币',
    'nav.btcPrice': 'BTC价格',
    'nav.tapProfile': '点击查看个人资料',
    'nav.closeMenu': '关闭菜单',
    'nav.faqLink': '常见问题',
    'demo.banner': '演示模式 — 使用示例数据探索。无需账户。',
    'demo.tryWishlist': '试用演示心愿单 →',
    'pwa.installTitle': '将KATOA添加到主屏幕',
    'pwa.installSubtitle': '快速访问，类似应用的体验。',
    'pwa.install': '安装',
    'pwa.dismiss': '关闭',
    'changelog.gotIt': '知道了',
    'changelog.whatsNew': '新功能',
    'common.backHome': '返回首页',
    'wishlist.title': '心愿单',
    'auth.passwordWeak': '密码较弱',
    'auth.passwordMedium': '密码中等',
    'auth.passwordStrong': '密码较强',
  },
};

const pageStrings = {
  en: {
    'dashboard.title': 'Creator Dashboard',
    'dashboard.subtitle': 'Manage your projects and track your success',
    'dashboard.loading': 'Loading your dashboard...',
    'dashboard.projects': 'Projects',
    'dashboard.wishlists': 'Wishlists',
    'dashboard.raised': 'Total Raised',
    'dashboard.createProject': 'Create Project',
    'dashboard.demo': 'Demo preview — UI only. Connect Supabase to save projects and accept real payments.',
    'wishlist.loading': 'Loading wishlist...',
    'wishlist.notFound': 'Wishlist Not Found',
    'wishlist.notFoundDesc': "This wishlist doesn't exist or has been removed.",
    'wishlist.sendGift': 'Send Gift',
    'wishlist.supportItems': 'Support specific items in this wishlist',
    'wishlist.explore': 'Explore Wishlists',
    'about.hero.line1': 'The Platform That',
    'about.hero.highlight': 'Actually Serves Creators',
    'about.hero.subtitle': "We're not just another platform. We're a movement.",
    'about.hero.badge': 'Built by creators, for creators',
    'about.problem.title': 'The Creator Economy is Broken',
    'about.problem.subtitle': 'Traditional platforms extract too much. Here\'s how much creators lose:',
    'comparison.hero.line1': 'Why Choose',
    'comparison.hero.highlight': 'KATOA?',
    'comparison.hero.subtitle': "We're not just another creator platform. We're built on Bitcoin Lightning, designed for global creators, and committed to 0% fees forever.",
    'comparison.saveMonthly': 'Save up to ${amount}/month with KATOA',
    'explore.allProjects': 'Explore All Projects',
    'explore.loadMore': 'Load more',
    'explore.remaining': 'remaining',
    ...aboutComparisonEn,
  },
  es: {
    'dashboard.title': 'Panel del Creador',
    'dashboard.subtitle': 'Gestiona tus proyectos y sigue tu éxito',
    'dashboard.loading': 'Cargando tu panel...',
    'dashboard.projects': 'Proyectos',
    'dashboard.wishlists': 'Listas',
    'dashboard.raised': 'Total recaudado',
    'dashboard.createProject': 'Crear proyecto',
    'dashboard.demo': 'Vista demo — solo UI. Conecta Supabase para guardar proyectos y aceptar pagos reales.',
    'wishlist.loading': 'Cargando lista...',
    'wishlist.notFound': 'Lista no encontrada',
    'wishlist.notFoundDesc': 'Esta lista no existe o ha sido eliminada.',
    'wishlist.sendGift': 'Enviar regalo',
    'wishlist.supportItems': 'Apoya artículos específicos de esta lista',
    'wishlist.explore': 'Explorar listas',
    'about.hero.line1': 'La plataforma que',
    'about.hero.highlight': 'realmente sirve a los creadores',
    'about.hero.subtitle': 'No somos otra plataforma más. Somos un movimiento.',
    'about.hero.badge': 'Hecho por creadores, para creadores',
    'about.problem.title': 'La economía creadora está rota',
    'about.problem.subtitle': 'Las plataformas tradicionales extraen demasiado. Esto es lo que pierden los creadores:',
    'comparison.hero.line1': 'Por qué elegir',
    'comparison.hero.highlight': 'KATOA?',
    'comparison.hero.subtitle': 'No somos otra plataforma de creadores. Estamos construidos sobre Bitcoin Lightning, diseñados para creadores globales, con 0% de comisiones para siempre.',
    'comparison.saveMonthly': 'Ahorra hasta ${amount}/mes con KATOA',
    'explore.allProjects': 'Explorar todos los proyectos',
    'explore.loadMore': 'Cargar más',
    'explore.remaining': 'restantes',
    ...aboutComparisonEs,
  },
  pt: {
    'dashboard.title': 'Painel do Criador',
    'dashboard.subtitle': 'Gerencie seus projetos e acompanhe seu sucesso',
    'dashboard.loading': 'Carregando seu painel...',
    'dashboard.projects': 'Projetos',
    'dashboard.wishlists': 'Listas',
    'dashboard.raised': 'Total arrecadado',
    'dashboard.createProject': 'Criar projeto',
    'dashboard.demo': 'Prévia demo — apenas UI. Conecte o Supabase para salvar projetos e aceitar pagamentos reais.',
    'wishlist.loading': 'Carregando lista...',
    'wishlist.notFound': 'Lista não encontrada',
    'wishlist.notFoundDesc': 'Esta lista não existe ou foi removida.',
    'wishlist.sendGift': 'Enviar presente',
    'wishlist.supportItems': 'Apoie itens específicos desta lista',
    'wishlist.explore': 'Explorar listas',
    'about.hero.line1': 'A plataforma que',
    'about.hero.highlight': 'realmente serve criadores',
    'about.hero.subtitle': 'Não somos mais uma plataforma. Somos um movimento.',
    'about.hero.badge': 'Feito por criadores, para criadores',
    'about.problem.title': 'A economia criativa está quebrada',
    'about.problem.subtitle': 'Plataformas tradicionais extraem demais. Veja quanto os criadores perdem:',
    'comparison.hero.line1': 'Por que escolher',
    'comparison.hero.highlight': 'KATOA?',
    'comparison.hero.subtitle': 'Não somos mais uma plataforma de criadores. Somos construídos no Bitcoin Lightning, para criadores globais, com 0% de taxas para sempre.',
    'comparison.saveMonthly': 'Economize até ${amount}/mês com KATOA',
    'explore.allProjects': 'Explorar todos os projetos',
    'explore.loadMore': 'Carregar mais',
    'explore.remaining': 'restantes',
    ...aboutComparisonPt,
  },
  fr: {
    'dashboard.title': 'Tableau de bord créateur',
    'dashboard.subtitle': 'Gérez vos projets et suivez votre succès',
    'dashboard.loading': 'Chargement du tableau de bord...',
    'dashboard.projects': 'Projets',
    'dashboard.wishlists': 'Listes',
    'dashboard.raised': 'Total collecté',
    'dashboard.createProject': 'Créer un projet',
    'dashboard.demo': 'Aperçu démo — UI uniquement. Connectez Supabase pour enregistrer des projets et accepter de vrais paiements.',
    'wishlist.loading': 'Chargement de la liste...',
    'wishlist.notFound': 'Liste introuvable',
    'wishlist.notFoundDesc': 'Cette liste n\'existe pas ou a été supprimée.',
    'wishlist.sendGift': 'Envoyer un cadeau',
    'wishlist.supportItems': 'Soutenez des articles spécifiques de cette liste',
    'wishlist.explore': 'Explorer les listes',
    'about.hero.line1': 'La plateforme qui',
    'about.hero.highlight': 'sert vraiment les créateurs',
    'about.hero.subtitle': 'Nous ne sommes pas une plateforme de plus. Nous sommes un mouvement.',
    'about.hero.badge': 'Conçu par des créateurs, pour des créateurs',
    'about.problem.title': 'L\'économie créative est cassée',
    'about.problem.subtitle': 'Les plateformes traditionnelles prélèvent trop. Voici ce que les créateurs perdent :',
    'comparison.hero.line1': 'Pourquoi choisir',
    'comparison.hero.highlight': 'KATOA ?',
    'comparison.hero.subtitle': 'Nous ne sommes pas une plateforme de plus. Nous sommes construits sur Bitcoin Lightning, pour les créateurs du monde entier, avec 0 % de frais pour toujours.',
    'comparison.saveMonthly': 'Économisez jusqu\'à ${amount}/mois avec KATOA',
    'explore.allProjects': 'Explorer tous les projets',
    'explore.loadMore': 'Charger plus',
    'explore.remaining': 'restants',
    ...aboutComparisonFr,
  },
  de: {
    'dashboard.title': 'Creator-Dashboard',
    'dashboard.subtitle': 'Verwalte deine Projekte und verfolge deinen Erfolg',
    'dashboard.loading': 'Dashboard wird geladen...',
    'dashboard.projects': 'Projekte',
    'dashboard.wishlists': 'Wunschlisten',
    'dashboard.raised': 'Gesamt gesammelt',
    'dashboard.createProject': 'Projekt erstellen',
    'dashboard.demo': 'Demo-Vorschau — nur UI. Verbinde Supabase, um Projekte zu speichern und echte Zahlungen zu akzeptieren.',
    'wishlist.loading': 'Wunschliste wird geladen...',
    'wishlist.notFound': 'Wunschliste nicht gefunden',
    'wishlist.notFoundDesc': 'Diese Wunschliste existiert nicht oder wurde entfernt.',
    'wishlist.sendGift': 'Geschenk senden',
    'wishlist.supportItems': 'Unterstütze bestimmte Artikel auf dieser Wunschliste',
    'wishlist.explore': 'Listen entdecken',
    'about.hero.line1': 'Die Plattform, die',
    'about.hero.highlight': 'Creator wirklich dient',
    'about.hero.subtitle': 'Wir sind nicht nur eine weitere Plattform. Wir sind eine Bewegung.',
    'about.hero.badge': 'Von Creatorn für Creator',
    'about.problem.title': 'Die Creator-Ökonomie ist kaputt',
    'about.problem.subtitle': 'Traditionelle Plattformen nehmen zu viel. So viel verlieren Creator:',
    'comparison.hero.line1': 'Warum',
    'comparison.hero.highlight': 'KATOA?',
    'comparison.hero.subtitle': 'Wir sind nicht nur eine Creator-Plattform. Wir basieren auf Bitcoin Lightning, für Creator weltweit, mit 0 % Gebühren für immer.',
    'comparison.saveMonthly': 'Spare bis zu ${amount}/Monat mit KATOA',
    'explore.allProjects': 'Alle Projekte entdecken',
    'explore.loadMore': 'Mehr laden',
    'explore.remaining': 'übrig',
    ...aboutComparisonDe,
  },
  ja: {
    'dashboard.title': 'クリエイターダッシュボード',
    'dashboard.subtitle': 'プロジェクトを管理し、成果を追跡',
    'dashboard.loading': 'ダッシュボードを読み込み中...',
    'dashboard.projects': 'プロジェクト',
    'dashboard.wishlists': 'ウィッシュリスト',
    'dashboard.raised': '総支援額',
    'dashboard.createProject': 'プロジェクト作成',
    'dashboard.demo': 'デモプレビュー — UIのみ。Supabaseを接続してプロジェクトを保存し、実際の支払いを受け付けてください。',
    'wishlist.loading': 'ウィッシュリストを読み込み中...',
    'wishlist.notFound': 'ウィッシュリストが見つかりません',
    'wishlist.notFoundDesc': 'このウィッシュリストは存在しないか、削除されました。',
    'wishlist.sendGift': 'ギフトを送る',
    'wishlist.supportItems': 'このリストの特定のアイテムを支援',
    'wishlist.explore': 'リストを探す',
    'about.hero.line1': 'クリエイターに',
    'about.hero.highlight': '本当に役立つプラットフォーム',
    'about.hero.subtitle': '私たちは単なるプラットフォームではありません。ムーブメントです。',
    'about.hero.badge': 'クリエイターによる、クリエイターのための',
    'about.problem.title': 'クリエイター経済は壊れている',
    'about.problem.subtitle': '従来のプラットフォームは取りすぎです。クリエイターが失う金額：',
    'comparison.hero.line1': 'なぜ',
    'comparison.hero.highlight': 'KATOA？',
    'comparison.hero.subtitle': '単なるクリエイタープラットフォームではありません。Bitcoin Lightning上に構築され、世界中のクリエイター向け、永久0%手数料です。',
    'comparison.saveMonthly': 'KATOAで月最大${amount}節約',
    'explore.allProjects': 'すべてのプロジェクトを探す',
    'explore.loadMore': 'もっと読み込む',
    'explore.remaining': '件残り',
    ...aboutComparisonJa,
  },
  zh: {
    'dashboard.title': '创作者仪表板',
    'dashboard.subtitle': '管理项目并追踪成果',
    'dashboard.loading': '正在加载仪表板...',
    'dashboard.projects': '项目',
    'dashboard.wishlists': '心愿单',
    'dashboard.raised': '总筹集额',
    'dashboard.createProject': '创建项目',
    'dashboard.demo': '演示预览 — 仅UI。连接Supabase以保存项目并接受真实付款。',
    'wishlist.loading': '正在加载心愿单...',
    'wishlist.notFound': '未找到心愿单',
    'wishlist.notFoundDesc': '此心愿单不存在或已被删除。',
    'wishlist.sendGift': '发送礼物',
    'wishlist.supportItems': '支持此心愿单中的特定物品',
    'wishlist.explore': '探索心愿单',
    'about.hero.line1': '真正',
    'about.hero.highlight': '为创作者服务的平台',
    'about.hero.subtitle': '我们不只是另一个平台。我们是一场运动。',
    'about.hero.badge': '由创作者打造，为创作者服务',
    'about.problem.title': '创作者经济已经崩溃',
    'about.problem.subtitle': '传统平台抽取太多。以下是创作者损失的金额：',
    'comparison.hero.line1': '为什么选择',
    'comparison.hero.highlight': 'KATOA？',
    'comparison.hero.subtitle': '我们不只是另一个创作者平台。基于比特币闪电网络，为全球创作者设计，永久零费用。',
    'comparison.saveMonthly': '使用KATOA每月最多节省${amount}',
    'explore.allProjects': '探索所有项目',
    'explore.loadMore': '加载更多',
    'explore.remaining': '剩余',
    ...aboutComparisonZh,
  },
};

const commonStrings = {
  en: {
    'common.loading': 'Loading...',
    'a11y.skipToContent': 'Skip to content',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.go': 'Go',
    'common.learnMore': 'Learn more',
    'common.getStarted': 'Get Started',
    'common.signIn': 'Sign In',
    'common.signUp': 'Sign Up',
    'onboarding.badge': '60-second setup',
    'onboarding.title': 'Quick start checklist',
    'onboarding.subtitle': 'Tick these off to launch your first wishlist',
    'onboarding.item.account': 'Create your free account',
    'onboarding.item.wallet': 'Add a Lightning address',
    'onboarding.item.wishlist': 'Create your first wishlist',
    'onboarding.item.share': 'Share your public page',
    'common.delete': 'Delete',
    'confirm.deleteWishlist.title': 'Delete Wishlist',
    'confirm.deleteWishlist.message': 'Are you sure you want to delete this wishlist? This cannot be undone.',
    'confirm.deleteAddress.title': 'Delete Address',
    'confirm.deleteAddress.message': 'Are you sure you want to delete this payment address?',
    'confirm.deletePaymentMethod.title': 'Delete Payment Method',
    'confirm.deletePaymentMethod.message': 'Are you sure you want to delete this payment method?',
    'confirm.deleteProject.title': 'Delete Project',
    'confirm.deleteProject.message': 'Are you sure you want to delete this project? This will also delete all associated wishlists.',
    'error.createProject': 'Failed to create project',
    'error.deleteProject': 'Failed to delete project',
    'error.updateProject': 'Failed to update project',
    'error.uploadBackground': 'Failed to upload background',
    'error.createWishlist': 'Failed to create wishlist',
    'error.deleteWishlist': 'Failed to delete wishlist',
    'error.updateWishlist': 'Failed to update wishlist',
    'error.addAddress': 'Failed to add address',
    'error.deleteAddress': 'Failed to delete address',
    'error.savePaymentMethod': 'Failed to save payment method',
    'error.deletePaymentMethod': 'Failed to delete payment method',
    'error.updateProfile': 'Failed to update profile',
    'error.uploadAvatar': 'Failed to upload avatar',
    'error.uploadBanner': 'Failed to upload banner',
    'error.qrImageScan': 'QR scanning from image requires additional library. Please paste the address manually.',
    'success.deleted': 'Deleted successfully',
    'success.saved': 'Saved successfully',
  },
  es: {
    'common.loading': 'Cargando...',
    'a11y.skipToContent': 'Saltar al contenido',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.create': 'Crear',
    'common.search': 'Buscar',
    'common.go': 'Ir',
    'common.learnMore': 'Saber más',
    'common.getStarted': 'Comenzar',
    'common.signIn': 'Iniciar sesión',
    'common.signUp': 'Registrarse',
    'onboarding.badge': 'Configuración en 60 segundos',
    'onboarding.title': 'Lista de inicio rápido',
    'onboarding.subtitle': 'Marca estos pasos para lanzar tu primera lista',
    'onboarding.item.account': 'Crea tu cuenta gratis',
    'onboarding.item.wallet': 'Añade una dirección Lightning',
    'onboarding.item.wishlist': 'Crea tu primera lista',
    'onboarding.item.share': 'Comparte tu página pública',
    'common.delete': 'Eliminar',
    'confirm.deleteWishlist.title': 'Eliminar lista',
    'confirm.deleteWishlist.message': '¿Seguro que quieres eliminar esta lista? No se puede deshacer.',
    'confirm.deleteAddress.title': 'Eliminar dirección',
    'confirm.deleteAddress.message': '¿Seguro que quieres eliminar esta dirección de pago?',
    'confirm.deletePaymentMethod.title': 'Eliminar método de pago',
    'confirm.deletePaymentMethod.message': '¿Seguro que quieres eliminar este método de pago?',
    'confirm.deleteProject.title': 'Eliminar proyecto',
    'confirm.deleteProject.message': '¿Seguro que quieres eliminar este proyecto? También se eliminarán todas las listas asociadas.',
    'error.createProject': 'Error al crear el proyecto',
    'error.deleteProject': 'Error al eliminar el proyecto',
    'error.updateProject': 'Error al actualizar el proyecto',
    'error.uploadBackground': 'Error al subir el fondo',
    'error.createWishlist': 'Error al crear la lista',
    'error.deleteWishlist': 'Error al eliminar la lista',
    'error.updateWishlist': 'Error al actualizar la lista',
    'error.addAddress': 'Error al añadir la dirección',
    'error.deleteAddress': 'Error al eliminar la dirección',
    'error.savePaymentMethod': 'Error al guardar el método de pago',
    'error.deletePaymentMethod': 'Error al eliminar el método de pago',
    'error.updateProfile': 'Error al actualizar el perfil',
    'error.uploadAvatar': 'Error al subir el avatar',
    'error.uploadBanner': 'Error al subir el banner',
    'error.qrImageScan': 'El escaneo QR desde imagen requiere una biblioteca adicional. Pega la dirección manualmente.',
    'success.deleted': 'Eliminado correctamente',
    'success.saved': 'Guardado correctamente',
  },
  pt: {
    'common.loading': 'Carregando...',
    'a11y.skipToContent': 'Ir para o conteúdo',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.create': 'Criar',
    'common.search': 'Pesquisar',
    'common.go': 'Ir',
    'common.learnMore': 'Saiba mais',
    'common.getStarted': 'Começar',
    'common.signIn': 'Entrar',
    'common.signUp': 'Cadastrar',
    'onboarding.badge': 'Configuração em 60 segundos',
    'onboarding.title': 'Checklist de início rápido',
    'onboarding.subtitle': 'Marque estes itens para lançar sua primeira lista',
    'onboarding.item.account': 'Crie sua conta gratuita',
    'onboarding.item.wallet': 'Adicione um endereço Lightning',
    'onboarding.item.wishlist': 'Crie sua primeira lista',
    'onboarding.item.share': 'Compartilhe sua página pública',
    'common.delete': 'Excluir',
    'confirm.deleteWishlist.title': 'Excluir lista',
    'confirm.deleteWishlist.message': 'Tem certeza que deseja excluir esta lista? Isso não pode ser desfeito.',
    'confirm.deleteAddress.title': 'Excluir endereço',
    'confirm.deleteAddress.message': 'Tem certeza que deseja excluir este endereço de pagamento?',
    'confirm.deletePaymentMethod.title': 'Excluir método de pagamento',
    'confirm.deletePaymentMethod.message': 'Tem certeza que deseja excluir este método de pagamento?',
    'confirm.deleteProject.title': 'Excluir projeto',
    'confirm.deleteProject.message': 'Tem certeza que deseja excluir este projeto? Todas as listas associadas também serão excluídas.',
    'error.createProject': 'Falha ao criar projeto',
    'error.deleteProject': 'Falha ao excluir projeto',
    'error.updateProject': 'Falha ao atualizar projeto',
    'error.uploadBackground': 'Falha ao enviar fundo',
    'error.createWishlist': 'Falha ao criar lista',
    'error.deleteWishlist': 'Falha ao excluir lista',
    'error.updateWishlist': 'Falha ao atualizar lista',
    'error.addAddress': 'Falha ao adicionar endereço',
    'error.deleteAddress': 'Falha ao excluir endereço',
    'error.savePaymentMethod': 'Falha ao salvar método de pagamento',
    'error.deletePaymentMethod': 'Falha ao excluir método de pagamento',
    'error.updateProfile': 'Falha ao atualizar perfil',
    'error.uploadAvatar': 'Falha ao enviar avatar',
    'error.uploadBanner': 'Falha ao enviar banner',
    'error.qrImageScan': 'Escaneamento QR de imagem requer biblioteca adicional. Cole o endereço manualmente.',
    'success.deleted': 'Excluído com sucesso',
    'success.saved': 'Salvo com sucesso',
  },
  fr: {
    'common.loading': 'Chargement...',
    'a11y.skipToContent': 'Aller au contenu',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.create': 'Créer',
    'common.search': 'Rechercher',
    'common.go': 'Aller',
    'common.learnMore': 'En savoir plus',
    'common.getStarted': 'Commencer',
    'common.signIn': 'Connexion',
    'common.signUp': 'S\'inscrire',
    'onboarding.badge': 'Configuration en 60 secondes',
    'onboarding.title': 'Liste de démarrage rapide',
    'onboarding.subtitle': 'Cochez ces étapes pour lancer votre première liste',
    'onboarding.item.account': 'Créez votre compte gratuit',
    'onboarding.item.wallet': 'Ajoutez une adresse Lightning',
    'onboarding.item.wishlist': 'Créez votre première liste',
    'onboarding.item.share': 'Partagez votre page publique',
    'common.delete': 'Supprimer',
    'confirm.deleteWishlist.title': 'Supprimer la liste',
    'confirm.deleteWishlist.message': 'Êtes-vous sûr de vouloir supprimer cette liste ? Cette action est irréversible.',
    'confirm.deleteAddress.title': 'Supprimer l\'adresse',
    'confirm.deleteAddress.message': 'Êtes-vous sûr de vouloir supprimer cette adresse de paiement ?',
    'confirm.deletePaymentMethod.title': 'Supprimer le mode de paiement',
    'confirm.deletePaymentMethod.message': 'Êtes-vous sûr de vouloir supprimer ce mode de paiement ?',
    'confirm.deleteProject.title': 'Supprimer le projet',
    'confirm.deleteProject.message': 'Êtes-vous sûr de vouloir supprimer ce projet ? Toutes les listes associées seront également supprimées.',
    'error.createProject': 'Échec de la création du projet',
    'error.deleteProject': 'Échec de la suppression du projet',
    'error.updateProject': 'Échec de la mise à jour du projet',
    'error.uploadBackground': 'Échec du téléchargement de l\'arrière-plan',
    'error.createWishlist': 'Échec de la création de la liste',
    'error.deleteWishlist': 'Échec de la suppression de la liste',
    'error.updateWishlist': 'Échec de la mise à jour de la liste',
    'error.addAddress': 'Échec de l\'ajout de l\'adresse',
    'error.deleteAddress': 'Échec de la suppression de l\'adresse',
    'error.savePaymentMethod': 'Échec de l\'enregistrement du mode de paiement',
    'error.deletePaymentMethod': 'Échec de la suppression du mode de paiement',
    'error.updateProfile': 'Échec de la mise à jour du profil',
    'error.uploadAvatar': 'Échec du téléchargement de l\'avatar',
    'error.uploadBanner': 'Échec du téléchargement de la bannière',
    'error.qrImageScan': 'Le scan QR depuis une image nécessite une bibliothèque supplémentaire. Collez l\'adresse manuellement.',
    'success.deleted': 'Supprimé avec succès',
    'success.saved': 'Enregistré avec succès',
  },
  de: {
    'common.loading': 'Laden...',
    'a11y.skipToContent': 'Zum Inhalt springen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.create': 'Erstellen',
    'common.search': 'Suchen',
    'common.go': 'Los',
    'common.learnMore': 'Mehr erfahren',
    'common.getStarted': 'Loslegen',
    'common.signIn': 'Anmelden',
    'common.signUp': 'Registrieren',
    'onboarding.badge': '60-Sekunden-Setup',
    'onboarding.title': 'Schnellstart-Checkliste',
    'onboarding.subtitle': 'Hake diese Punkte ab, um deine erste Wunschliste zu starten',
    'onboarding.item.account': 'Kostenloses Konto erstellen',
    'onboarding.item.wallet': 'Lightning-Adresse hinzufügen',
    'onboarding.item.wishlist': 'Erste Wunschliste erstellen',
    'onboarding.item.share': 'Öffentliche Seite teilen',
    'common.delete': 'Löschen',
    'confirm.deleteWishlist.title': 'Wunschliste löschen',
    'confirm.deleteWishlist.message': 'Möchtest du diese Wunschliste wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
    'confirm.deleteAddress.title': 'Adresse löschen',
    'confirm.deleteAddress.message': 'Möchtest du diese Zahlungsadresse wirklich löschen?',
    'confirm.deletePaymentMethod.title': 'Zahlungsmethode löschen',
    'confirm.deletePaymentMethod.message': 'Möchtest du diese Zahlungsmethode wirklich löschen?',
    'confirm.deleteProject.title': 'Projekt löschen',
    'confirm.deleteProject.message': 'Möchtest du dieses Projekt wirklich löschen? Alle zugehörigen Wunschlisten werden ebenfalls gelöscht.',
    'error.createProject': 'Projekt konnte nicht erstellt werden',
    'error.deleteProject': 'Projekt konnte nicht gelöscht werden',
    'error.updateProject': 'Projekt konnte nicht aktualisiert werden',
    'error.uploadBackground': 'Hintergrund konnte nicht hochgeladen werden',
    'error.createWishlist': 'Wunschliste konnte nicht erstellt werden',
    'error.deleteWishlist': 'Wunschliste konnte nicht gelöscht werden',
    'error.updateWishlist': 'Wunschliste konnte nicht aktualisiert werden',
    'error.addAddress': 'Adresse konnte nicht hinzugefügt werden',
    'error.deleteAddress': 'Adresse konnte nicht gelöscht werden',
    'error.savePaymentMethod': 'Zahlungsmethode konnte nicht gespeichert werden',
    'error.deletePaymentMethod': 'Zahlungsmethode konnte nicht gelöscht werden',
    'error.updateProfile': 'Profil konnte nicht aktualisiert werden',
    'error.uploadAvatar': 'Avatar konnte nicht hochgeladen werden',
    'error.uploadBanner': 'Banner konnte nicht hochgeladen werden',
    'error.qrImageScan': 'QR-Scan aus Bild erfordert eine zusätzliche Bibliothek. Bitte Adresse manuell einfügen.',
    'success.deleted': 'Erfolgreich gelöscht',
    'success.saved': 'Erfolgreich gespeichert',
  },
  ja: {
    'common.loading': '読み込み中...',
    'a11y.skipToContent': 'コンテンツへスキップ',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.create': '作成',
    'common.search': '検索',
    'common.go': '移動',
    'common.learnMore': '詳しく見る',
    'common.getStarted': '始める',
    'common.signIn': 'ログイン',
    'common.signUp': '新規登録',
    'onboarding.badge': '60秒セットアップ',
    'onboarding.title': 'クイックスタートチェックリスト',
    'onboarding.subtitle': '最初のウィッシュリストを公開するためのステップ',
    'onboarding.item.account': '無料アカウントを作成',
    'onboarding.item.wallet': 'Lightningアドレスを追加',
    'onboarding.item.wishlist': '最初のウィッシュリストを作成',
    'onboarding.item.share': '公開ページを共有',
    'common.delete': '削除',
    'confirm.deleteWishlist.title': 'ウィッシュリストを削除',
    'confirm.deleteWishlist.message': 'このウィッシュリストを削除してもよろしいですか？元に戻せません。',
    'confirm.deleteAddress.title': 'アドレスを削除',
    'confirm.deleteAddress.message': 'この支払いアドレスを削除してもよろしいですか？',
    'confirm.deletePaymentMethod.title': '支払い方法を削除',
    'confirm.deletePaymentMethod.message': 'この支払い方法を削除してもよろしいですか？',
    'confirm.deleteProject.title': 'プロジェクトを削除',
    'confirm.deleteProject.message': 'このプロジェクトを削除してもよろしいですか？関連するウィッシュリストもすべて削除されます。',
    'error.createProject': 'プロジェクトの作成に失敗しました',
    'error.deleteProject': 'プロジェクトの削除に失敗しました',
    'error.updateProject': 'プロジェクトの更新に失敗しました',
    'error.uploadBackground': '背景のアップロードに失敗しました',
    'error.createWishlist': 'ウィッシュリストの作成に失敗しました',
    'error.deleteWishlist': 'ウィッシュリストの削除に失敗しました',
    'error.updateWishlist': 'ウィッシュリストの更新に失敗しました',
    'error.addAddress': 'アドレスの追加に失敗しました',
    'error.deleteAddress': 'アドレスの削除に失敗しました',
    'error.savePaymentMethod': '支払い方法の保存に失敗しました',
    'error.deletePaymentMethod': '支払い方法の削除に失敗しました',
    'error.updateProfile': 'プロフィールの更新に失敗しました',
    'error.uploadAvatar': 'アバターのアップロードに失敗しました',
    'error.uploadBanner': 'バナーのアップロードに失敗しました',
    'error.qrImageScan': '画像からのQRスキャンには追加ライブラリが必要です。アドレスを手動で貼り付けてください。',
    'success.deleted': '削除しました',
    'success.saved': '保存しました',
  },
  zh: {
    'common.loading': '加载中...',
    'a11y.skipToContent': '跳转到内容',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.create': '创建',
    'common.search': '搜索',
    'common.go': '前往',
    'common.learnMore': '了解更多',
    'common.getStarted': '开始使用',
    'common.signIn': '登录',
    'common.signUp': '注册',
    'onboarding.badge': '60秒设置',
    'onboarding.title': '快速入门清单',
    'onboarding.subtitle': '勾选这些步骤以发布你的第一个心愿单',
    'onboarding.item.account': '创建免费账户',
    'onboarding.item.wallet': '添加闪电地址',
    'onboarding.item.wishlist': '创建第一个心愿单',
    'onboarding.item.share': '分享你的公开页面',
    'common.delete': '删除',
    'confirm.deleteWishlist.title': '删除心愿单',
    'confirm.deleteWishlist.message': '确定要删除此心愿单吗？此操作无法撤销。',
    'confirm.deleteAddress.title': '删除地址',
    'confirm.deleteAddress.message': '确定要删除此支付地址吗？',
    'confirm.deletePaymentMethod.title': '删除支付方式',
    'confirm.deletePaymentMethod.message': '确定要删除此支付方式吗？',
    'confirm.deleteProject.title': '删除项目',
    'confirm.deleteProject.message': '确定要删除此项目吗？所有关联的心愿单也将被删除。',
    'error.createProject': '创建项目失败',
    'error.deleteProject': '删除项目失败',
    'error.updateProject': '更新项目失败',
    'error.uploadBackground': '上传背景失败',
    'error.createWishlist': '创建心愿单失败',
    'error.deleteWishlist': '删除心愿单失败',
    'error.updateWishlist': '更新心愿单失败',
    'error.addAddress': '添加地址失败',
    'error.deleteAddress': '删除地址失败',
    'error.savePaymentMethod': '保存支付方式失败',
    'error.deletePaymentMethod': '删除支付方式失败',
    'error.updateProfile': '更新个人资料失败',
    'error.uploadAvatar': '上传头像失败',
    'error.uploadBanner': '上传横幅失败',
    'error.qrImageScan': '从图片扫描二维码需要额外库。请手动粘贴地址。',
    'success.deleted': '删除成功',
    'success.saved': '保存成功',
  },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.explore': 'Explore',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'hero.title': 'Fund Dreams with Bitcoin',
    'hero.subtitle': 'Create wishlists, share your story, and receive Bitcoin support from around the world',
    'hero.cta': 'Get Started',
    'hero.explore': 'Explore Wishlists',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.pricing': 'Pricing',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.tagline': 'Empowering dreams with Bitcoin',
    'explore.title': 'Explore Wishlists',
    'explore.subtitle': 'Discover amazing creators and support their dreams around the world',
    'explore.search': 'Search wishlists...',
    'explore.allCountries': 'All Countries',
    'explore.showMap': 'Show Map',
    'explore.hideMap': 'Hide Map',
    'explore.mapTitle': 'Wishlists Around the World',
    'explore.raised': 'raised',
    'explore.noResults': 'No results found',
    'explore.tryAgain': 'Try adjusting your filters',
    'about.title': 'About Katoa',
    'about.subtitle': 'Our Mission',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in Touch',
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Simple, Transparent',
    ...homeStrings.en,
    ...navUiStrings.en,
    ...commonStrings.en,
    ...pageStrings.en,
  },
  es: {
    'nav.explore': 'Explorar',
    'nav.dashboard': 'Panel',
    'nav.settings': 'Ajustes',
    'nav.login': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'hero.title': 'Financia Sueños con Bitcoin',
    'hero.subtitle': 'Crea listas de deseos, comparte tu historia y recibe apoyo en Bitcoin de todo el mundo',
    'hero.cta': 'Comenzar',
    'hero.explore': 'Explorar Listas',
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
    'footer.pricing': 'Precios',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    'footer.tagline': 'Empoderando sueños con Bitcoin',
    'explore.title': 'Explorar Listas de Deseos',
    'explore.subtitle': 'Descubre creadores increíbles y apoya sus sueños en todo el mundo',
    'explore.search': 'Buscar listas...',
    'explore.allCountries': 'Todos los Países',
    'explore.showMap': 'Mostrar Mapa',
    'explore.hideMap': 'Ocultar Mapa',
    'explore.mapTitle': 'Listas de Deseos en el Mundo',
    'explore.raised': 'recaudado',
    'explore.noResults': 'No se encontraron resultados',
    'explore.tryAgain': 'Intenta ajustar tus filtros',
    'about.title': 'Acerca de Katoa',
    'about.subtitle': 'Nuestra Misión',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en Contacto',
    'pricing.title': 'Precios',
    'pricing.subtitle': 'Simple y Transparente',
    ...homeStrings.es,
    ...navUiStrings.es,
    ...commonStrings.es,
    ...pageStrings.es,
  },
  pt: {
    'nav.explore': 'Explorar',
    'nav.dashboard': 'Painel',
    'nav.settings': 'Configurações',
    'nav.login': 'Entrar',
    'nav.signup': 'Cadastrar',
    'hero.title': 'Financie Sonhos com Bitcoin',
    'hero.subtitle': 'Crie listas de desejos, compartilhe sua história e receba apoio em Bitcoin do mundo todo',
    'hero.cta': 'Começar',
    'hero.explore': 'Explorar Listas',
    'footer.about': 'Sobre',
    'footer.contact': 'Contato',
    'footer.pricing': 'Preços',
    'footer.terms': 'Termos de Serviço',
    'footer.privacy': 'Política de Privacidade',
    'footer.tagline': 'Capacitando sonhos com Bitcoin',
    'explore.title': 'Explorar Listas de Desejos',
    'explore.subtitle': 'Descubra criadores incríveis e apoie seus sonhos ao redor do mundo',
    'explore.search': 'Pesquisar listas...',
    'explore.allCountries': 'Todos os Países',
    'explore.showMap': 'Mostrar Mapa',
    'explore.hideMap': 'Esconder Mapa',
    'explore.mapTitle': 'Listas de Desejos pelo Mundo',
    'explore.raised': 'arrecadado',
    'explore.noResults': 'Nenhum resultado encontrado',
    'explore.tryAgain': 'Tente ajustar seus filtros',
    'about.title': 'Sobre Katoa',
    'about.subtitle': 'Nossa Missão',
    'contact.title': 'Fale Conosco',
    'contact.subtitle': 'Entre em Contato',
    'pricing.title': 'Preços',
    'pricing.subtitle': 'Simples e Transparente',
    ...homeStrings.pt,
    ...navUiStrings.pt,
    ...commonStrings.pt,
    ...pageStrings.pt,
  },
  fr: {
    'nav.explore': 'Explorer',
    'nav.dashboard': 'Tableau de Bord',
    'nav.settings': 'Paramètres',
    'nav.login': 'Connexion',
    'nav.signup': 'S\'inscrire',
    'hero.title': 'Financez des Rêves avec Bitcoin',
    'hero.subtitle': 'Créez des listes de souhaits, partagez votre histoire et recevez du soutien Bitcoin du monde entier',
    'hero.cta': 'Commencer',
    'hero.explore': 'Explorer les Listes',
    'footer.about': 'À Propos',
    'footer.contact': 'Contact',
    'footer.pricing': 'Tarifs',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.tagline': 'Donner vie aux rêves avec Bitcoin',
    'explore.title': 'Explorer les Listes de Souhaits',
    'explore.subtitle': 'Découvrez des créateurs incroyables et soutenez leurs rêves à travers le monde',
    'explore.search': 'Rechercher des listes...',
    'explore.allCountries': 'Tous les Pays',
    'explore.showMap': 'Afficher la Carte',
    'explore.hideMap': 'Masquer la Carte',
    'explore.mapTitle': 'Listes de Souhaits dans le Monde',
    'explore.raised': 'collecté',
    'explore.noResults': 'Aucun résultat trouvé',
    'explore.tryAgain': 'Essayez d\'ajuster vos filtres',
    'about.title': 'À Propos de Katoa',
    'about.subtitle': 'Notre Mission',
    'contact.title': 'Nous Contacter',
    'contact.subtitle': 'Prenez Contact',
    'pricing.title': 'Tarifs',
    'pricing.subtitle': 'Simple et Transparent',
    ...homeStrings.fr,
    ...navUiStrings.fr,
    ...commonStrings.fr,
    ...pageStrings.fr,
  },
  de: {
    'nav.explore': 'Entdecken',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Einstellungen',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'hero.title': 'Finanziere Träume mit Bitcoin',
    'hero.subtitle': 'Erstelle Wunschlisten, teile deine Geschichte und erhalte Bitcoin-Unterstützung aus der ganzen Welt',
    'hero.cta': 'Loslegen',
    'hero.explore': 'Listen Entdecken',
    'footer.about': 'Über Uns',
    'footer.contact': 'Kontakt',
    'footer.pricing': 'Preise',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.privacy': 'Datenschutz',
    'footer.tagline': 'Träume verwirklichen mit Bitcoin',
    'explore.title': 'Wunschlisten Entdecken',
    'explore.subtitle': 'Entdecke erstaunliche Kreative und unterstütze ihre Träume weltweit',
    'explore.search': 'Listen durchsuchen...',
    'explore.allCountries': 'Alle Länder',
    'explore.showMap': 'Karte Anzeigen',
    'explore.hideMap': 'Karte Verbergen',
    'explore.mapTitle': 'Wunschlisten Weltweit',
    'explore.raised': 'gesammelt',
    'explore.noResults': 'Keine Ergebnisse gefunden',
    'explore.tryAgain': 'Versuche deine Filter anzupassen',
    'about.title': 'Über Katoa',
    'about.subtitle': 'Unsere Mission',
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Melde Dich',
    'pricing.title': 'Preise',
    'pricing.subtitle': 'Einfach und Transparent',
    ...homeStrings.de,
    ...navUiStrings.de,
    ...commonStrings.de,
    ...pageStrings.de,
  },
  ja: {
    'nav.explore': '探索',
    'nav.dashboard': 'ダッシュボード',
    'nav.settings': '設定',
    'nav.login': 'ログイン',
    'nav.signup': '新規登録',
    'hero.title': 'Bitcoinで夢を応援',
    'hero.subtitle': 'ウィッシュリストを作成し、あなたのストーリーを共有して、世界中からBitcoinサポートを受け取りましょう',
    'hero.cta': '始める',
    'hero.explore': 'リストを探す',
    'footer.about': '私たちについて',
    'footer.contact': 'お問い合わせ',
    'footer.pricing': '料金',
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシーポリシー',
    'footer.tagline': 'Bitcoinで夢を実現',
    'explore.title': 'ウィッシュリストを探す',
    'explore.subtitle': '素晴らしいクリエイターを発見し、世界中の夢を応援しよう',
    'explore.search': 'リストを検索...',
    'explore.allCountries': 'すべての国',
    'explore.showMap': '地図を表示',
    'explore.hideMap': '地図を非表示',
    'explore.mapTitle': '世界中のウィッシュリスト',
    'explore.raised': '達成',
    'explore.noResults': '結果が見つかりません',
    'explore.tryAgain': 'フィルターを調整してください',
    'about.title': 'Katoaについて',
    'about.subtitle': '私たちのミッション',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'ご連絡ください',
    'pricing.title': '料金',
    'pricing.subtitle': 'シンプルで透明',
    ...homeStrings.ja,
    ...navUiStrings.ja,
    ...commonStrings.ja,
    ...pageStrings.ja,
  },
  zh: {
    'nav.explore': '探索',
    'nav.dashboard': '仪表板',
    'nav.settings': '设置',
    'nav.login': '登录',
    'nav.signup': '注册',
    'hero.title': '用比特币资助梦想',
    'hero.subtitle': '创建心愿单，分享您的故事，并从世界各地获得比特币支持',
    'hero.cta': '开始使用',
    'hero.explore': '探索心愿单',
    'footer.about': '关于我们',
    'footer.contact': '联系我们',
    'footer.pricing': '定价',
    'footer.terms': '服务条款',
    'footer.privacy': '隐私政策',
    'footer.tagline': '用比特币实现梦想',
    'explore.title': '探索心愿单',
    'explore.subtitle': '发现了不起的创作者，支持他们在全世界的梦想',
    'explore.search': '搜索心愿单...',
    'explore.allCountries': '所有国家',
    'explore.showMap': '显示地图',
    'explore.hideMap': '隐藏地图',
    'explore.mapTitle': '世界各地的心愿单',
    'explore.raised': '已筹集',
    'explore.noResults': '未找到结果',
    'explore.tryAgain': '尝试调整您的筛选条件',
    'about.title': '关于 Katoa',
    'about.subtitle': '我们的使命',
    'contact.title': '联系我们',
    'contact.subtitle': '保持联系',
    'pricing.title': '定价',
    'pricing.subtitle': '简单透明',
    ...homeStrings.zh,
    ...navUiStrings.zh,
    ...commonStrings.zh,
    ...pageStrings.zh,
  },
};

export const languageFlags: Record<Language, string> = {
  en: '🇬🇧',
  es: '🇪🇸',
  pt: '🇧🇷',
  fr: '🇫🇷',
  de: '🇩🇪',
  ja: '🇯🇵',
  zh: '🇨🇳',
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  pt: 'Português',
  fr: 'Français',
  de: 'Deutsch',
  ja: '日本語',
  zh: '中文',
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(resolveInitialLanguage);

  useEffect(() => {
    localStorage.setItem('katoa-language', language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    const urlLang = new URLSearchParams(window.location.search).get('lang');
    if (urlLang && isValidLanguage(urlLang) && urlLang !== language) {
      setLanguageState(urlLang);
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
