import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, LockKeyhole, Sparkles } from 'lucide-react';
import { DemoBadge } from './DemoBadge';

export function CinematicCheckout({ amountSats, recipient, isDemo, children, onBack }: { amountSats?: number; recipient: string; isDemo: boolean; children: React.ReactNode; onBack: () => void }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { const frame = window.requestAnimationFrame(() => setMounted(true)); return () => window.cancelAnimationFrame(frame); }, []);
  return <div className={`relative overflow-hidden rounded-[1.75rem] border border-white/10 bg-gradient-to-b from-[#24152f] via-charcoal-900 to-charcoal-950 transition-all duration-500 ${mounted ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-2'}`} data-testid="cinematic-checkout">
    <div className="absolute -right-20 -top-24 h-56 w-56 rounded-full bg-bitcoin-orange-500/15 blur-3xl" aria-hidden /><div className="absolute -left-20 top-1/3 h-48 w-48 rounded-full bg-neon-cyan-500/10 blur-3xl" aria-hidden />
    <div className="relative border-b border-white/10 px-4 py-5 sm:px-6"><button type="button" onClick={onBack} className="mb-5 inline-flex min-h-[40px] items-center gap-2 text-xs font-bold text-gray-400 hover:text-white"><ArrowLeft size={15} /> Back to amount</button><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-[0.2em] text-bitcoin-orange-300"><Sparkles size={13} /> Focused checkout</p><h2 className="mt-2 text-2xl font-black text-white">Support @{recipient}</h2><p className="mt-1 text-sm text-gray-400">One clear payment journey. No clutter.</p></div>{isDemo && <DemoBadge label="Demo" />}</div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Step label="Choose" done /><Step label="Pay" active /><Step label="Confirm" locked /></div></div>
    <div className="relative space-y-5 p-4 sm:p-6"><div className="flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><span className="text-xs font-bold uppercase tracking-wider text-gray-500">Support amount</span><span className="text-lg font-black text-white">{amountSats ? `${amountSats.toLocaleString()} sats` : 'Selected amount'}</span></div>{children}<div className="flex items-center justify-center gap-2 text-[11px] text-gray-600"><LockKeyhole size={13} /> Wallet-controlled · backend-confirmed settlement</div></div>
  </div>;
}

function Step({ label, done, active, locked }: { label: string; done?: boolean; active?: boolean; locked?: boolean }) { return <div className={`rounded-xl border px-2 py-2 ${active ? 'border-bitcoin-orange-500/40 bg-bitcoin-orange-500/10' : done ? 'border-emerald-500/25 bg-emerald-500/10' : 'border-white/10 bg-white/[0.02]'}`}><div className="flex justify-center">{done ? <CheckCircle2 size={14} className="text-emerald-300" /> : locked ? <LockKeyhole size={14} className="text-gray-600" /> : <span className="h-3.5 w-3.5 rounded-full border border-bitcoin-orange-300" />}</div><p className={`mt-1 text-[10px] font-bold ${active ? 'text-bitcoin-orange-200' : done ? 'text-emerald-200' : 'text-gray-500'}`}>{label}</p></div>; }
