import { Activity, ArrowUpRight, Clock3, FileCheck2, Heart, Target, TrendingUp, Users } from 'lucide-react';
import { Card } from './Card';
import { DemoPreviewBadge } from './DemoPreviewBadge';

export interface ImpactGoal { id: string; title: string; raised: number; goal: number; detail: string; }
export interface ImpactUpdate { id: string; title: string; detail: string; date: string; }

export function CreatorImpactDashboard({ goals, updates, satsRaised, supporterCount, demo = false }: { goals: ImpactGoal[]; updates: ImpactUpdate[]; satsRaised: number; supporterCount?: number; demo?: boolean }) {
  const totalGoal = goals.reduce((sum, goal) => sum + goal.goal, 0);
  const totalRaised = goals.reduce((sum, goal) => sum + goal.raised, 0);
  const progress = totalGoal ? Math.min(100, Math.round((totalRaised / totalGoal) * 100)) : 0;
  return <section className="mb-14" aria-labelledby="impact-dashboard-heading" data-testid="creator-impact-dashboard">
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-neon-cyan-300">Impact dashboard</p><h2 id="impact-dashboard-heading" className="mt-1 font-display text-2xl font-black text-white sm:text-3xl">See what support changes</h2><p className="mt-1 text-sm text-gray-500">Goals, milestones, updates, and proof in one glance.</p></div>{demo && <DemoPreviewBadge compact />}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mb-4"><Metric icon={<TrendingUp size={17} />} label="Raised" value={`${satsRaised.toLocaleString()} sats`} tone="orange" /><Metric icon={<Target size={17} />} label="Overall progress" value={`${progress}%`} tone="cyan" /><Metric icon={<Users size={17} />} label="Supporters" value={supporterCount === undefined ? 'Not tracked' : supporterCount.toLocaleString()} tone="violet" /><Metric icon={<Heart size={17} />} label="Creator keeps" value="100%" tone="green" /></div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
      <Card variant="glass" className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3 mb-5"><div><h3 className="text-lg font-black text-white">Goals and milestones</h3><p className="text-xs text-gray-500">Each goal explains where the next sats go.</p></div><Activity size={19} className="text-neon-cyan-300" /></div><div className="space-y-4">{goals.map((goal) => { const pct = goal.goal ? Math.min(100, Math.round((goal.raised / goal.goal) * 100)) : 0; return <div key={goal.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold text-white">{goal.title}</p><p className="mt-1 text-xs leading-relaxed text-gray-500">{goal.detail}</p></div><span className="shrink-0 text-xs font-bold text-neon-cyan-200">{pct}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-bitcoin-orange-500 to-neon-cyan-400" style={{ width: `${pct}%` }} /></div><p className="mt-1 text-[10px] text-gray-600">{goal.raised.toLocaleString()} / {goal.goal.toLocaleString()} sats</p></div>; })}</div></Card>
      <Card variant="glass" className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3 mb-5"><div><h3 className="text-lg font-black text-white">Progress updates</h3><p className="text-xs text-gray-500">Small updates build long-term trust.</p></div><Clock3 size={19} className="text-bitcoin-orange-300" /></div><div className="space-y-4">{updates.map((update) => <div key={update.id} className="relative pl-5"><span className="absolute left-0 top-1.5 h-2 w-2 rounded-full bg-neon-cyan-300" /><p className="text-sm font-bold text-white">{update.title}</p><p className="mt-1 text-xs leading-relaxed text-gray-400">{update.detail}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-gray-600">{update.date}</p></div>)}</div><div className="mt-5 border-t border-white/10 pt-4"><div className="flex items-center gap-2 text-xs font-bold text-emerald-200"><FileCheck2 size={14} /> Proof remains separately auditable</div><p className="mt-1 text-[11px] leading-relaxed text-gray-500">Payment totals and release proof are different claims. Check both instead of trusting a badge.</p><a href="/verify" className="mt-2 inline-flex min-h-[36px] items-center gap-1 text-xs font-bold text-neon-cyan-200">Open proof verifier <ArrowUpRight size={13} /></a></div></Card>
    </div>
  </section>;
}

function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: 'orange' | 'cyan' | 'violet' | 'green' }) {
  const colors = { orange: 'text-bitcoin-orange-300 bg-bitcoin-orange-500/10', cyan: 'text-neon-cyan-300 bg-neon-cyan-500/10', violet: 'text-violet-300 bg-violet-500/10', green: 'text-emerald-300 bg-emerald-500/10' };
  return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><span className={`inline-flex rounded-xl p-2 ${colors[tone]}`}>{icon}</span><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-gray-500">{label}</p><p className="mt-1 text-xl font-black text-white">{value}</p></div>;
}
