/**
 * Writes deploy version metadata shown in the site footer.
 *
 * Every build gets a unique label:
 *   v{package.version}+{commitCount}  (e.g. v1.1.0+1523)
 *   or on CI: v{package.version}+run.{GITHUB_RUN_NUMBER}
 *
 * Set KATOA_BUMP_PACKAGE=1 to also bump package.json patch (recommended
 * before each intentional ship from M3 agents).
 *
 * Outputs:
 *   src/generated/app-version.ts
 *   public/version.json
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const pkgPath = join(root, 'package.json');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

function bumpPatch(version) {
  const parts = String(version || '0.0.0').split('.').map((n) => parseInt(n, 10) || 0);
  while (parts.length < 3) parts.push(0);
  parts[2] += 1;
  return parts.slice(0, 3).join('.');
}

const shouldBump =
  process.env.KATOA_BUMP_PACKAGE === '1' ||
  process.env.KATOA_BUMP_PACKAGE === 'true' ||
  process.argv.includes('--bump');

const previous = pkg.version || '1.0.0';
let next = process.env.KATOA_VERSION_OVERRIDE || previous;

if (shouldBump && !process.env.KATOA_VERSION_OVERRIDE) {
  next = bumpPatch(previous);
  pkg.version = next;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

let gitSha = 'unknown';
let gitCount = '0';
try {
  gitSha = execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  /* ignore */
}
try {
  gitCount = execSync('git rev-list --count HEAD', { cwd: root, encoding: 'utf8' }).trim();
} catch {
  /* ignore */
}

const builtAt = new Date().toISOString();
const runNumber = process.env.GITHUB_RUN_NUMBER || '';
const buildId = runNumber
  ? `run.${runNumber}`
  : process.env.CF_PAGES_COMMIT_SHA?.slice(0, 7) || `${gitCount}.${gitSha}`;

const label = `v${next}`;
// Unique every deploy: semver + build id (commit count / GH run)
const fullLabel = `${label}+${buildId}`;

const genDir = join(root, 'src', 'generated');
mkdirSync(genDir, { recursive: true });

const ts = `/** Auto-generated by scripts/write-version.mjs — do not edit */
export const APP_VERSION = ${JSON.stringify(next)};
export const APP_VERSION_LABEL = ${JSON.stringify(label)};
export const APP_BUILD_ID = ${JSON.stringify(String(buildId))};
export const APP_VERSION_FULL = ${JSON.stringify(fullLabel)};
export const APP_BUILT_AT = ${JSON.stringify(builtAt)};
export const APP_GIT_SHA = ${JSON.stringify(gitSha)};
export const APP_GIT_COMMIT_COUNT = ${JSON.stringify(gitCount)};
`;

writeFileSync(join(genDir, 'app-version.ts'), ts, 'utf8');

writeFileSync(
  join(root, 'public', 'version.json'),
  JSON.stringify(
    {
      name: 'katoa',
      version: next,
      label,
      fullLabel,
      buildId: String(buildId),
      gitSha,
      commitCount: gitCount,
      builtAt,
    },
    null,
    2
  ) + '\n',
  'utf8'
);

console.log(`version: ${previous}${shouldBump ? ` → ${next}` : ''}  footer: ${fullLabel}`);
